### ISSUE TITLE
sqlite3.OperationalError: unable to open database file 

### ISSUE THREAD

**Issue by zhao-newname** [mmdfish/StockIndicatorAnalyzer#2]
Hello
In my ubuntu run the python3 run_first_time.py
```
zjp@zjp-HP-Laptop ~/w/StockIndicatorAnalyzer (master)> python3 run_first_time.py                                                                                                                                   
login success!                                                                                                                                                                                                     
logout success!                                                                                                                                                                                                    
2006-01-01 2020-08-25                                                                                                                                                                                              
start to refresh all stock                                                                                                                                                                                         
login success!                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect                                                                                                  
    return fn()                                                                                                                                                                                                    
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect                                                                                                                
    return _ConnectionFairy._checkout(self)                                                                                                                                                                        
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout                                                                                                              
    fairy = _ConnectionRecord.checkout(pool)                                                                                                                                                                       
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout                                                                                                               
    rec = pool._do_get()                                                                                                                                                                                           
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get                                                                                                                
    return self._create_connection()                                                                                                                                                                               
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection                                                                                                     
    return _ConnectionRecord(self)                                                                                                                                                                                 
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__                                                                                                               
    self.__connect(first_connect_check=True)                                                                                                                                                                       
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect                                                                                                              
    pool.logger.debug("Error on connect(): %s", e)                                                                                                                                                                 
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(                                                                                       
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/zjp/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception
```

```
zjp@zjp-HP-Laptop ~/w/StockIndicatorAnalyzer (master)> grep -r "mystock.db"
common.py:db_path_sqlite3 = r'/home/zjp/workstaging/StockIndicatorAnalyzer/mystock.db'
common.py:db_path_sqlalchemy = r'sqlite:///home/zjp/workstaging/StockIndicatorAnalyzer/mystock.db'
Binary file __pycache__/common.cpython-38.pyc matches

```

**Comment by mmdfish** [comment]
How about you test if sqlalchemy works first

from sqlalchemy import create_engine
db = create_engine("you database path")

**Comment by mmdfish** [comment]
Fixed， I commented the create database code before for test

**Comment by zhao-newname** [comment]
change the common.py file
replace 
```
db_path_sqlalchemy = 'sqlite:///home/zjp/workstaging/StockIndicatorAnalyzer/mystock.db'
```
with
```
db_path_sqlalchemy = 'sqlite:////home/zjp/workstaging/StockIndicatorAnalyzer/mystock.db'
```
