### ISSUE TITLE
ValueError: 0 is not in range

### ISSUE THREAD

**Issue by zhao-newname** [mmdfish/StockIndicatorAnalyzer#4]
run the command "python3 run_first_time.py"
```
.......

984 sh.600917 重庆燃气
985 sh.600918 中泰证券
Traceback (most recent call last):
  File "/home/zjp/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 346, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_first_time.py", line 46, in <module>
    calculate_stock_spec.calculate_all_spec('sh', 'sh.000001')
  File "/home/zjp/workstaging/StockIndicatorAnalyzer/calculate_stock_spec.py", line 58, in calculate_all_spec
    daily['relaprice'] = daily['close']/daily['close'][0]
  File "/home/zjp/.local/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/home/zjp/.local/lib/python3.8/site-packages/pandas/core/series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "/home/zjp/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 348, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

**Comment by mmdfish** [comment]
Cannot  produce here, you can change calculate_stock_spec.py line 171 to sh.600918 and debug calculate_stock_spec.py to check what is wrong with this stock

if __name__=='__main__':
    starttime = datetime.datetime.now()
    **calculate_all_spec('sh.600918', 'sh.000001')**

    endtime = datetime.datetime.now()
    print(endtime - starttime)

**Comment by mmdfish** [comment]
你现在数据库已经生成，k线数据也都抓到了，可以运行daily_update.py了，因为你run_first_time.py没有运行完，所以没有生成date.txt，可以手动在同级目录下创建一个date.txt，内容是 2020-08-25

**Comment by zhao-newname** [comment]
```
-        
-        sql_cmd = "SELECT * FROM stock_day_k where code='" + ticker+"' and tradestatus='1' order by date desc limit 0,251"
-        daily = pd.read_sql(sql=sql_cmd, con=db)
+
+        sql_cmd_select = "SELECT * FROM stock_day_k where code='" + ticker+"' and tradestatus='1' order by date desc limit 0,251"
+        sql_cmd_delete = 'delete from allstock where code="%s"' % ticker
+        daily = pd.read_sql(sql=sql_cmd_select, con=db)
 
         daily = daily.sort_values(by='date', ascending=True)
         daily = daily.reset_index(drop = True)
-        daily['relaprice'] = daily['close']/daily['close'][0]
+        try:
+            daily['relaprice'] = daily['close']/daily['close'][0]
+        except Exception as e:
+            db.execute(sql_cmd_delete)
+            continue
         relaticker = daily['relaprice']
 ```

**Comment by zhao-newname** [comment]
> 你现在数据库已经生成，k线数据也都抓到了，可以运行daily_update.py了，因为你run_first_time.py没有运行完，所以没有生成date.txt，可以手动在同级目录下创建一个date.txt，内容是 2020-08-25

thanks for your reply

**Comment by mmdfish** [comment]
> -        
> -        sql_cmd = "SELECT * FROM stock_day_k where code='" + ticker+"' and tradestatus='1' order by date desc limit 0,251"
> -        daily = pd.read_sql(sql=sql_cmd, con=db)
> +
> +        sql_cmd_select = "SELECT * FROM stock_day_k where code='" + ticker+"' and tradestatus='1' order by date desc limit 0,251"
> +        sql_cmd_delete = 'delete from allstock where code="%s"' % ticker
> +        daily = pd.read_sql(sql=sql_cmd_select, con=db)
>  
>          daily = daily.sort_values(by='date', ascending=True)
>          daily = daily.reset_index(drop = True)
> -        daily['relaprice'] = daily['close']/daily['close'][0]
> +        try:
> +            daily['relaprice'] = daily['close']/daily['close'][0]
> +        except Exception as e:
> +            db.execute(sql_cmd_delete)
> +            continue
>          relaticker = daily['relaprice']

最好还是看一看这个股票的数据有什么问题

**Comment by Jamesvips** [comment]
运行命令“ python3 run_first_time.py”
......
adjust sz.399997
adjust sz.399998
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
接收数据异常，请稍后再试。
start to calculate sh
1 sh.000002 上证A股指数
2 sh.000003 上证B股指数
......
976 sh.600909 华安证券
977 sh.600916 中国黄金
Traceback (most recent call last):
  File "C:\Users\jamsg\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\range.py", line 355, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/jamsg/Documents/GitHub/StockIndicatorAnalyzer/run_first_time.py", line 46, in <module>
    calculate_stock_spec.calculate_all_spec('sh', 'sh.000001')
  File "c:\Users\jamsg\Documents\GitHub\StockIndicatorAnalyzer\calculate_stock_spec.py", line 58, in calculate_all_spec
    daily['relaprice'] = daily['close']/daily['close'][0]
  File "C:\Users\jamsg\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\series.py", line 882, in __getitem__
    return self._get_value(key)
  File "C:\Users\jamsg\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\jamsg\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\range.py", line 357, in get_loc
    raise KeyError(key) from err
